version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
    # Add reviewers
    reviewers:
      - "sunui-design/core-team"
    # Add assignees
    assignees:
      - "sunui-design/core-team"
    # Limit to 5 open pull requests for version updates
    open-pull-requests-limit: 5
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # 添加以下設置
    versioning-strategy: increase
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "@sunui-design/*"  # 忽略內部包的更新
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope" 