name: CI

on:
  push:
    branches:
      - '**'  # matches all branches
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Clean install dependencies
      run: |
        npm install
        npm run build:packages
        
    - name: Run linting
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
      
    - name: Run tests
      run: npm test
      
    - name: Build Storybook
      run: npm run build-storybook

    - name: Check if PR to master
      if: failure() && github.event_name == 'pull_request' && github.base_ref == 'master'
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const { number } = context.payload.pull_request;
          
          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body: `❌ CI Build Failed\n\nView failure details: ${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}`
          });

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Clean and install dependencies
      run: |
        rm -rf node_modules
        rm -rf packages/*/node_modules
        rm -f package-lock.json
        npm install
        npm run build:packages
    
    - name: Run Snyk to check for vulnerabilities
      # Only run Snyk on trusted sources
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

    - name: Skip Snyk for untrusted PR
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
      run: |
        echo "Skipping Snyk security check for PR from fork"
        echo "For security reasons, Snyk checks are only run on internal PRs"

    - name: Check if PR to master
      if: failure() && github.event_name == 'pull_request' && github.base_ref == 'master'
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const { number } = context.payload.pull_request;
          
          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body: `❌ Security Check Failed\n\nView failure details: ${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}`
          }); 