name: Issue Management

on:
  issues:
    types: [opened, labeled]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.issue.labels;
            const hasBug = labels.some(l => l.name === 'bug');
            const hasFeature = labels.some(l => l.name === 'enhancement');
            
            if (hasBug && !hasFeature) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['needs-triage']
              });
            } 